<div class="textContent">
    <div  style="text-align: center"><h1>Impressum</h1></div>
    <br />
    Impressum Initiator Prof. Dr. Hans-Gert Gr&auml;be<br />
    <br />
    Universit&auml;t Leipzig Fakult&auml;t f&uuml;r Mathematik und Informatik Institut f&uuml;r Informatik PF 100920 04009 Leipzig<br />
    <br />
    Gesch&auml;ftsf&uuml;hrender Direktor: Prof. Dr. Gerik Scheuermann<br />
    <br />
    Universit&auml;t Leipzig Ritterstra&szlig;e 26 04109 Leipzig<br />
    <br />
    Rechtsform Die Universit&auml;t Leipzig ist eine K&ouml;rperschaft des &Ouml;ffentlichen Rechts. Sie wird durch die Rektorin Prof. Dr. med. Beate A. Sch&uuml;cking gesetzlich vertreten.<br />
    <br />
    Zust&auml;ndige Aufsichtsbeh&ouml;rde S&auml;chsisches Staatsministerium f&uuml;r Wissenschaft und Kunst Wigardstra&szlig;e 17 01097 Dresden www.smwk.de<br />
    <br />
    Umsatzsteuer-Identifikationsnummer gem&auml;&szlig; &sect; 27 a Umsatzsteuergesetz DE 141510383<br />
    <br />
    Die &bdquo;Erneuerbare Energien Karte&ldquo; wurde von einer interdisziplin&auml;ren Studentengruppe der Universit&auml;t Leipzig im Rahmen eines Praktikums erstellt.<br />
    <br />
    Beratung und Betreuung Prof. Dr. Hans-Gert Gr&auml;be Institut f&uuml;r Informatik der Universit&auml;t Leipzig Augustusplatz 10 Tel. (+49)-0341-97-32248 email:graebe@informatik.uni-leipzig.de<br />
    <br />
    Webdesign Phillip Holl&auml;nder<br />
    <br />
    Bildquellen XXXX<br />
    <br />
    Disclaimer Unser Angebot enth&auml;lt Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. F&uuml;r die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. F&uuml;r die Inhalte und die Richtigkeit der Informationen verlinkter Websites fremder Informationsanbieter wird keine Gew&auml;hr &uuml;bernommen.<br />
    <br />
    Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielf&auml;ltigung, Bearbeitung, Verbreitung und jede Art der Verwertung au&szlig;erhalb der Grenzen des Urheberrechtes bed&uuml;rfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers.<br />
    <br />
    Haftungsausschluss Die Inhalte dieser Website wurden mit gr&ouml;&szlig;tm&ouml;glicher Sorgfalt und nach bestem Wissen erstellt. Da Fehler jedoch nie auszuschlie&szlig;en sind und die Daten sowie weitere Inhalte Ver&auml;nderungen unterliegen k&ouml;nnen, weisen wir auf Folgendes hin: Wir &uuml;bernehmen keine Gew&auml;hr f&uuml;r die Aktualit&auml;t, Richtigkeit, Vollst&auml;ndigkeit oder Qualit&auml;t der auf dieser Website bereitgestellten Informationen. F&uuml;r Sch&auml;den materieller oder immaterieller Art, die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung fehlerhafter und unvollst&auml;ndiger Informationen unmittelbar oder mittelbar verursacht werden, haften wir nicht, sofern nicht nachweislich vors&auml;tzliches oder grob fahrl&auml;ssiges Verschulden zur Last gelegt werden kann.<br />
    <br />
    <br />
    Datenbasis Es wurden die Anlagenstammdaten, die unter der Ver&ouml;ffentlichungspflicht der Netzbetreiber nach &sect; 52 EEG stehen von folgenden Anbietern verwendet:<br />
    <br />
    Mitnetz Leipzig <a href="https://www.mitnetz-strom.de/irj/go/km/docs/z_ep_em_unt_documents/em/mitnetzstrom/Dokumente/Stammdaten_EEG-Jahresmeldung_2012_MITNETZ%20STROM.pdf">Link</a>Stand: 2012<br />
    <br />
    EEG KWK <a href="http://www.eeg-kwk.net/de/Anlagenstammdaten.htm">Link</a>Stand: 2012<br />
    <br />
    Netz Leipzig <a href="http://www.netz-leipzig.de/netzanschluesse/erzeugungsanlagen/?eID=dam_frontend_push&docID=358">Link</a>Stand: 2012<br />
    <br />
    50Hertz <a href="http://www.50hertz.com/cps/rde/xchg/trm_de/hs.xsl/165.htm">Link</a>Stand: 2012<br />
    <br />
    Karte erstellt mit <a href="http://leafletjs.com">Leaflet</a><br />
</div>
<div class="clear"></div>