<div class="textContent">
    <p>Willkommen auf der &bdquo;Erneuerbare Energien Map Leipzig&ldquo;</p>
    <br />
    <p>Hier finden Sie eine Karte mit allen dezentralen Energieerzeugungsanlagen in Leipzig.</p>
    <br />
    <p>
        <b>Der Hintergrund</b><br />
        &bdquo;Erneuerbare Energien sind der Schl&uuml;ssel zu einer nachhaltigen Energieversorgung&ldquo; - so wird es gesellschaftspolitisch diskutiert und praktiziert.
        Das Gesetz zum Vorrang Erneuerbarer Energien (kurz EEG) formuliert die Wende von fossilen, ersch&ouml;pflichen zu unersch&ouml;pflichen, alternativen Energietr&auml;gern, wie Solarstrahlung, Erdw&auml;rme und Windkraft. Dabei spielt nicht nur die Umsetzung dieses Vorhabens eine gro&szlig;e Rolle, sondern auch dessen Transparenz. Anlagenstammdaten zu erneuerbaren Energiequellen unterliegen laut &sect; 52 EEG der Ver&ouml;ffentlichungspflicht von Netzbetreibern (s. &bdquo;Gesetzliche Grundlage&ldquo;).
    </p>
    <br />
    <p>
        <b>Das Projekt</b><br />
        Im Wintersemester 2013/2014 hat sich ein interdisziplin&auml;res Projektteam am Institut f&uuml;r Informatik der Universit&auml;t Leipzig unter der Leitung von Prof. Dr. Hans-Gert Gr&auml;be zum Ziel gesetzt, die von den Netzbetreibern ver&ouml;ffentlichten Stammdaten zu sammeln, aufzubereiten und in einem Kataster zu visualisieren.
    </p>
    <br />
        <b>Die Idee</b><br />
        Ziel des Projektes ist es, nicht nur einen &Uuml;berblick &uuml;ber die Energiewende in Leipzig zu schaffen und diese &ouml;ffentlich diskutierbar zu machen, sondern eine Grundlage f&uuml;r weitere Dateneinpflegung, Funktionserweiterung und Aktualisierung zu schaffen. Unter der Philosophie von Open Data und der Verwendung des &bdquo;Linked Open Data&ldquo;-Konzeptes soll mit der e-Map Leipzig eine Basis f&uuml;r weiterf&uuml;hrende Vernetzung von offenen Daten in Leipzig erm&ouml;glicht werden. (siehe auch Leipzig Data: <a href="http://www.leipzig-data.de">www.leipzig-data.de</a>)
    </p>
    <br />
    <p>
        <b>Partizipation</b><br />
        Unter folgendem Link erhalten Sie Zugang zum OntoWiki der verwendeten Daten. Diese sind offen einsehbar und stehen zur weiteren Verlinkung bereit.<br />
        <a href="http://pcai042.informatik.uni-leipzig.de/~energie13/OntoWiki/">Link zum OntoWiki</a>
    </p>
</div>
<div class="clear"></div>